#define JUMP_X 8
#define JUMP_Y 4
#define CORR_COEFFICIENT_THRESHOLD 0.425
#define MEAN_THRESHOLD 30.00
#define MORPH_DILATION_FILTER 15 //17
#define BINARY_IMAGE_THRESHOLD 64.00 //98
#define CAR_TEMPLATE_NAME "Templates/template-car"
#define HOG_CELL_SIZE 8
#define HOG_BIN_SIZE 9
#define HOG_BIN_SEPERATION 20
#define HOG_BLOCK_SIZE 2
#define PI 3.14159265
#define NUMBER_OF_TEMPLATES 24
#define BLACK_PIXEL_COUNT 10
